version: '3'

networks:
  my-network:
    driver: bridge
services:

  db-streamhub:
    image: mysql:8
    container_name: db-streamhub
    environment:
      MYSQL_DATABASE: streamhub-api-gateway
      MYSQL_USER: gtwuser
      MYSQL_PASSWORD: gtwpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10
    networks:
      - my-network
  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/data

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-config/:/opt/keycloak/data/import/
volumes:
  redis:
    driver: local